Section 1 — Project Introduction, Loading Data, and Initial Exploration

# 🏥 Healthcare Feature Engineering Pipeline for Predictive Modeling

## Project Overview

Healthcare data originates from multiple independent systems, such as:

- Electronic Health Records (EHR)
- Laboratory Information Systems (LIS)
- Pharmacy Systems
- Billing Systems

These systems store information in different formats and structures.

Before data can be used for Artificial Intelligence (AI), Machine Learning (ML), or Business Intelligence (BI), it must be transformed into a structured and consistent format.

In this notebook, we will simulate a real healthcare data engineering pipeline using synthetic healthcare datasets.

The goal is to transform raw healthcare events into a **model-ready dataset** suitable for predictive analytics.

---

## 🏥 Healthcare Workflow

Raw Healthcare Data

↓

Data Exploration

↓

Feature Engineering

↓

Patient-Level Dataset

↓

Machine Learning / Dashboard

---

## Datasets

This project uses three healthcare datasets.

### 1. Encounter Dataset
Contains information about patient hospital visits.

Examples:
- Admission Date
- Discharge Date
- Encounter Type
- Diagnosis

---

### 2. Laboratory Dataset

Contains laboratory test results.

Examples:
- HbA1c
- Glucose
- Creatinine

---

### 3. Medication Dataset

Contains prescribed medications.

Examples:
- Drug Name
- Medication Class
- Prescription Date

---

## Project Objectives

By the end of this notebook we will learn how to:

✔ Aggregate laboratory results

✔ Count patient visits

✔ Calculate Length of Stay (LOS)

✔ Pivot long event tables

✔ Handle missing values

✔ Encode categorical variables

✔ Merge multiple healthcare datasets

✔ Build a model-ready dataset

✔ Prevent data leakage

This workflow closely resembles how healthcare organizations prepare data before training predictive AI models.

In [1]:
import pandas as pd
import numpy as np

# Display all columns when viewing DataFrames
pd.set_option("display.max_columns", None)

## 🧠 Code Pattern to Remember

Every healthcare analytics notebook starts with importing libraries.

```python
import pandas as pd
import numpy as np


---

# 📘 Markdown Cell

```markdown
# 📂 Step 2 — Load Healthcare Datasets

## 🏥 Real Hospital Scenario

Hospitals store patient information across multiple independent systems.

Instead of one large table, healthcare data is divided into specialized datasets.

For this project we will load:

- Encounter Data
- Laboratory Data
- Medication Data

Each dataset represents a different aspect of the patient's clinical journey.

---

## 🎯 What this code does

This code reads three CSV files into Pandas DataFrames.

Each DataFrame represents one healthcare data source.

---

## ❓Why do we load datasets separately?

Healthcare systems are siloed.

For example:

Electronic Health Record

↓

Patient Visits

Laboratory System

↓

Lab Tests

Pharmacy System

↓

Medications

Later in the notebook we will combine these datasets through feature engineering.

In [2]:
# Load datasets
encounters_df = pd.read_csv("encounters_dataset1.csv")
laboratory_df = pd.read_csv("laboratory_dataset1.csv")
medications_df = pd.read_csv("medications_dataset1.csv")

## 🧠 Code Pattern to Remember

Load CSV files using Pandas.

```python
df = pd.read_csv("filename.csv")


---

# 📘 Markdown Cell

```markdown
# 🔍 Step 3 — Preview Each Dataset

## 🏥 Real Hospital Scenario

Before transforming healthcare data, analysts always inspect the datasets.

This helps answer questions like:

- Did the data load correctly?
- What columns are available?
- Are there obvious data quality issues?

Data exploration is an essential first step in every healthcare analytics project.

---

## 🎯 What this code does

Displays the first five rows of each dataset.

---

## ❓Why do we use `.head()`?

Rather than displaying thousands of rows, `.head()` gives us a quick preview of the dataset's structure.

It helps verify that the data has been loaded correctly before any preprocessing begins.

In [3]:
print("=== Encounter Dataset ===")
display(encounters_df.head())

print("=== Laboratory Dataset ===")
display(laboratory_df.head())

print("=== Medication Dataset ===")
display(medications_df.head())

=== Encounter Dataset ===

  patient_id encounter_id encounter_date diagnosis_code
0      P0001     EP0001_1     2023-02-21            I10
1      P0001     EP0001_2     2023-03-13            E11
2      P0001     EP0001_3     2023-04-06            I10
3      P0001     EP0001_4     2023-04-10            E11
4      P0001     EP0001_5     2023-04-10            I10

=== Laboratory Dataset ===

  patient_id    lab_date lab_name  lab_value
0      P0001  2023-01-14  Glucose      157.0
1      P0001  2023-01-28  Glucose      102.3
2      P0001  2023-02-11  Glucose       90.5
3      P0001  2023-03-12  Glucose      140.9
4      P0002  2023-01-02  Glucose      137.2

=== Medication Dataset ===

  patient_id medication_name med_start_date
0      P0001      Lisinopril     2023-01-09
1      P0001       Metformin     2023-02-21
2      P0001      Lisinopril     2023-03-12
3      P0002      Lisinopril     2022-12-27
4      P0002      Lisinopril     2023-01-15

## 🧠 Code Pattern to Remember

```python
df.head()


---

# 📘 Markdown Cell

```markdown
# 📊 Step 4 — Understand Dataset Dimensions

## 🏥 Real Hospital Scenario

Healthcare datasets can contain millions of records.

One of the first questions analysts ask is:

- How many patients?
- How many encounters?
- How many laboratory results?

Knowing the size of the dataset helps estimate processing time and identify unexpected data issues.

---

## 🎯 What this code does

Displays the number of rows and columns in each dataset.

---

## ❓Why do we use `.shape`?

`.shape` quickly summarizes the size of a DataFrame.

It returns:

(Number of Rows, Number of Columns)

This is often the first validation check after loading healthcare data.

In [4]:
print("Encounter Dataset Shape:", encounters_df.shape)
print("Laboratory Dataset Shape:", laboratory_df.shape)
print("Medication Dataset Shape:", medications_df.shape)

Encounter Dataset Shape: (1851, 4)
Laboratory Dataset Shape: (1780, 4)
Medication Dataset Shape: (794, 3)

## 🧠 Code Pattern to Remember

```python
df.shape

Section 2 — Data Assessment & Quality Checks

# 🔍 Step 5 — Examine Data Types

## 🏥 Real Hospital Scenario

Healthcare data comes from multiple hospital systems.

Some systems store dates as text, laboratory results as strings, or numeric values in inconsistent formats.

Before performing any analysis, we need to understand how each column is stored.

---

## 🎯 What this code does

This code displays the data type of every column in each dataset.

---

## ❓Why do we use it?

Machine learning and analytics require the correct data types.

For example:

- Admission Date → Datetime
- Laboratory Result → Numeric
- Patient ID → Text
- Encounter Type → Category

If data types are incorrect, calculations may fail or produce incorrect results.

In [5]:
print("=== Encounter Dataset ===")
print(encounters_df.dtypes)

print("\n=== Laboratory Dataset ===")
print(laboratory_df.dtypes)

print("\n=== Medication Dataset ===")
print(medications_df.dtypes)

=== Encounter Dataset ===
patient_id        object
encounter_id      object
encounter_date    object
diagnosis_code    object
dtype: object

=== Laboratory Dataset ===
patient_id     object
lab_date       object
lab_name       object
lab_value     float64
dtype: object

=== Medication Dataset ===
patient_id         object
medication_name    object
med_start_date     object
dtype: object

## 🧠 Code Pattern to Remember

```python
df.dtypes
```

Think:

DataFrame

↓

Inspect Column Types

↓

Identify Conversion Needs

# 🔍 Step 6 — Check Missing Values

## 🏥 Real Hospital Scenario

Healthcare datasets are rarely complete.

Examples include:

- A laboratory test was never ordered.
- A discharge date is missing because the patient is still admitted.
- A medication was prescribed outside the hospital.

Missing values are common and must be identified before feature engineering.

---

## 🎯 What this code does

Counts missing values in every column.

---

## ❓Why do we use it?

Missing values can:

- Bias machine learning models
- Break calculations
- Produce misleading dashboards

Knowing where missing data exists helps us decide how to handle it later.

In [6]:
print("=== Encounter Missing Values ===")
print(encounters_df.isnull().sum())

print("\n=== Laboratory Missing Values ===")
print(laboratory_df.isnull().sum())

print("\n=== Medication Missing Values ===")
print(medications_df.isnull().sum())

=== Encounter Missing Values ===
patient_id        0
encounter_id      0
encounter_date    0
diagnosis_code    0
dtype: int64

=== Laboratory Missing Values ===
patient_id    0
lab_date      0
lab_name      0
lab_value     0
dtype: int64

=== Medication Missing Values ===
patient_id         0
medication_name    0
med_start_date     0
dtype: int64

## 🧠 Code Pattern to Remember

```python
df.isnull().sum()
```

Think:

Dataset

↓

Check Missing Values

↓

Plan Data Cleaning

# 📊 Step 7 — Generate Summary Statistics

## 🏥 Real Hospital Scenario

Healthcare analysts often ask:

- What is the average glucose level?
- What is the maximum hospital stay?
- What is the distribution of laboratory values?

Summary statistics provide a quick overview of the data.

---

## 🎯 What this code does

Generates descriptive statistics for numerical columns.

---

## ❓Why do we use it?

This helps identify:

- Typical values
- Extreme values
- Possible outliers
- Unexpected data quality issues

In [7]:
print("=== Laboratory Summary ===")
display(laboratory_df.describe())

print("=== Encounter Summary ===")
display(encounters_df.describe(include="all"))

=== Laboratory Summary ===

         lab_value
count  1780.000000
mean    119.517697
std      25.111057
min      40.600000
25%     102.475000
50%     118.900000
75%     136.125000
max     218.200000

=== Encounter Summary ===

       patient_id encounter_id encounter_date diagnosis_code
count        1851         1851           1851           1851
unique        400         1851            162              2
top         P0382     EP0400_5     2023-03-01            E11
freq            6            1             30            928

print("=== Laboratory Summary ===")
display(laboratory_df.describe())

print("=== Encounter Summary ===")
display(encounters_df.describe(include="all"))

# 🧪 Step 8 — Count Unique Patients

## 🏥 Real Hospital Scenario

A patient may have:

- Multiple hospital visits
- Multiple laboratory tests
- Multiple medication prescriptions

Before engineering features, we need to know how many unique patients are represented in each dataset.

---

## 🎯 What this code does

Counts the number of unique patient IDs in each dataset.

---

## ❓Why do we use it?

This validates that:

- Patient identifiers are consistent
- Datasets can later be merged successfully
- We understand the population size

In [8]:
print("Unique Patients in Encounters:",
      encounters_df["patient_id"].nunique())

print("Unique Patients in Laboratory:",
      laboratory_df["patient_id"].nunique())

print("Unique Patients in Medications:",
      medications_df["patient_id"].nunique())

Unique Patients in Encounters: 400
Unique Patients in Laboratory: 400
Unique Patients in Medications: 400

## 🧠 Code Pattern to Remember

```python
df["patient_id"].nunique()
```

Think:

Patient IDs

↓

Count Unique Patients

↓

Estimate Population Size

# 🔗 Step 9 — Verify Common Patient IDs Across Datasets

## 🏥 Real Hospital Scenario

Healthcare information is stored in separate systems.

For feature engineering to work, the same patient should appear across encounters, laboratory tests, and medications.

This step verifies that the datasets can be linked together.

---

## 🎯 What this code does

Compares patient IDs across the three datasets.

---

## ❓Why do we use it?

If patient IDs do not match:

- Feature tables cannot be merged correctly.
- Some patients may be lost during analysis.
- Machine learning datasets become incomplete.

This validation helps ensure successful data integration.

In [9]:
encounter_patients = set(encounters_df["patient_id"])
lab_patients = set(laboratory_df["patient_id"])
med_patients = set(medications_df["patient_id"])

common_patients = encounter_patients & lab_patients & med_patients

print("Patients present in all datasets:", len(common_patients))

Patients present in all datasets: 400

## 🧠 Code Pattern to Remember

```python
set(df["patient_id"])
```

Then compare sets using:

```python
&
```

Think:

Encounter Patients

+

Laboratory Patients

+

Medication Patients

↓

Common Patients

↓

Ready for Feature Engineering

Section 3 — Laboratory Feature Engineering

# 🧪 Introduction to Laboratory Feature Engineering

## 🏥 Real Hospital Scenario

Every day, hospitals generate thousands of laboratory results.

For one diabetic patient, the laboratory system might contain:

| Patient | Date | Test | Result |
|----------|------|------|--------|
| P001 | Jan 10 | Glucose | 180 |
| P001 | Jan 20 | Glucose | 165 |
| P001 | Feb 02 | HbA1c | 8.1 |
| P001 | Mar 15 | Creatinine | 1.2 |

This is called **event-level data** because every laboratory test is stored as a separate event.

However, machine learning models do not learn efficiently from thousands of individual events.

Instead, we summarize laboratory history into meaningful patient-level features.

---

## 🎯 In this section we will create

✔ Number of laboratory tests

✔ Average laboratory values

✔ Latest laboratory values

✔ Patient laboratory feature table

These features will later be merged with encounter and medication features to build our final AI dataset.

Step 1 — Explore Laboratory Events

# 🔍 Step 10 — Explore Laboratory Events

## 🏥 Real Hospital Scenario

Before building features, healthcare analysts first inspect the laboratory data.

Typical questions include:

- Which laboratory tests exist?
- How many patients have laboratory results?
- Are some tests repeated many times?

Understanding the raw events helps us decide which features to engineer.

---

## 🎯 What this code does

Displays the first laboratory records.

---

## ❓Why do we use it?

This helps us understand:

- Test names
- Patient IDs
- Dates
- Laboratory values

before we summarize them.

In [10]:
laboratory_df.head(10)

  patient_id    lab_date lab_name  lab_value
0      P0001  2023-01-14  Glucose      157.0
1      P0001  2023-01-28  Glucose      102.3
2      P0001  2023-02-11  Glucose       90.5
3      P0001  2023-03-12  Glucose      140.9
4      P0002  2023-01-02  Glucose      137.2
5      P0002  2023-01-15  Glucose      130.5
6      P0002  2023-02-09  Glucose      110.6
7      P0002  2023-02-01  Glucose      134.4
8      P0002  2023-01-30  Glucose       66.2
9      P0002  2023-02-16  Glucose      102.0

# 🧮 Step 11 — Count Laboratory Tests

## 🏥 Real Hospital Scenario

Some patients visit the laboratory frequently.

Example:

| Patient | Number of Lab Tests |
|----------|--------------------|
| P001 | 3 |
| P002 | 15 |
| P003 | 28 |

Patients requiring many laboratory tests often have more complex medical conditions.

Instead of storing every laboratory event, we summarize them into one feature.

---

## 🎯 What this code does

Counts the number of laboratory tests performed for each patient.

---

## ❓Why do we use it?

Laboratory utilization is often an important predictor of:

- Disease severity
- Healthcare utilization
- Hospital readmission

In [11]:
lab_counts = (
    laboratory_df
    .groupby("patient_id")
    .size()
    .reset_index(name="lab_test_count")
)

lab_counts.head()

  patient_id  lab_test_count
0      P0001               4
1      P0002               6
2      P0003               5
3      P0004               3
4      P0005               5

## 🧠 Code Pattern to Remember

```python
df.groupby("patient_id").size()
```

Think:

Many Lab Events

↓

Count Events

↓

One Patient Feature

Step 3 — Calculate Average Laboratory Values

# 📊 Step 12 — Calculate Average Laboratory Values

## 🏥 Real Hospital Scenario

A diabetic patient's glucose changes over time.

Example:

| Date | Glucose |
|------|---------|
| Jan | 180 |
| Feb | 170 |
| Mar | 190 |

Instead of using every measurement separately, analysts often calculate an average value.

Average glucose provides a more stable representation of the patient's health.

---

## 🎯 What this code does

Calculates the average laboratory result for each patient and laboratory test.

---

## ❓Why do we use it?

Averages reduce noise caused by day-to-day variation.

They provide a stable feature for predictive models.

In [14]:
average_labs = (
    laboratory_df
    .groupby(["patient_id", "lab_name"])["lab_value"]
    .mean()
    .reset_index()
)

average_labs.head()

  patient_id lab_name   lab_value
0      P0001  Glucose  122.675000
1      P0002  Glucose  113.483333
2      P0003  Glucose  125.480000
3      P0004  Glucose  130.600000
4      P0005  Glucose  128.780000

## 🧠 Code Pattern to Remember

```python
df.groupby(
    ["patient_id", "test_name"]
)["result_value"].mean()
```

Think:

Multiple Lab Results

↓

Average

↓

Stable Clinical Feature

Step 4 — Find the Latest Laboratory Resul

# 🕒 Step 13 — Latest Laboratory Result

## 🏥 Real Hospital Scenario

Doctors often care most about the patient's most recent laboratory result.

For example:

| Date | HbA1c |
|------|-------|
| Jan | 8.9 |
| Mar | 8.4 |
| Jun | 7.8 |

The latest HbA1c best reflects the patient's current condition.

---

## 🎯 What this code does

Keeps only the most recent laboratory result for each patient and laboratory test.

---

## ❓Why do we use it?

Recent laboratory values often predict future clinical outcomes better than older values.

In [17]:
laboratory_df["lab_date"] = pd.to_datetime(laboratory_df["lab_date"])

latest_labs = (
    laboratory_df
    .sort_values("lab_date")
    .groupby(["patient_id", "lab_name"])
    .last()
    .reset_index()
)

latest_labs.head()

  patient_id lab_name   lab_date  lab_value
0      P0001  Glucose 2023-03-12      140.9
1      P0002  Glucose 2023-02-16      102.0
2      P0003  Glucose 2023-02-26      140.2
3      P0004  Glucose 2023-01-15      139.0
4      P0005  Glucose 2023-02-26      187.0

## 🧠 Code Pattern to Remember

```python
sort_values()

↓

groupby()

↓

last()
```

Think:

Sort by Date

↓

Newest Record

↓

Latest Laboratory Feature

Step 5 — Pivot Laboratory Data (Long → Wide)

# 🔄 Step 14 — Pivot Laboratory Data

## 🏥 Real Hospital Scenario

Right now the laboratory data is stored in a **long format**.

| Patient | Test | Result |
|----------|------|--------|
| P001 | Glucose | 180 |
| P001 | HbA1c | 8.2 |
| P001 | Creatinine | 1.1 |

Machine learning models expect one row per patient.

We therefore convert the long table into a wide table.

---

## 🎯 What this code does

Creates one column for each laboratory test.

---

## ❓Why do we use it?

Machine learning algorithms work best when:

- One row = one patient
- One column = one feature

In [18]:
lab_features = average_labs.pivot(
    index="patient_id",
    columns="lab_name",
    values="lab_value"
).reset_index()

lab_features.head()

lab_name patient_id     Glucose
0             P0001  122.675000
1             P0002  113.483333
2             P0003  125.480000
3             P0004  130.600000
4             P0005  128.780000

## 🧠 Code Pattern to Remember

```python
pivot(
    index="patient_id",
    columns="test_name",
    values="result_value"
)
```

Think:

Long Table

↓

Pivot

↓

Wide Table

↓

AI Ready

Section 4 — Encounter Feature Engineering
This section transforms raw hospital encounters into patient-level features that machine learning models can use.

# 🏥 Introduction to Encounter Feature Engineering

## 🏥 Real Hospital Scenario

Every hospital visit creates a new encounter record.

For one patient, the encounter table might look like this:

| Patient | Encounter | Date | Diagnosis |
|----------|-----------|------|-----------|
| P0001 | EP001 | Jan 10 | E11 |
| P0001 | EP002 | Feb 18 | I10 |
| P0001 | EP003 | Mar 25 | E11 |

While clinicians view these as individual visits, AI models need a summarized view of each patient's healthcare utilization.

Instead of feeding every encounter into the model, we create features that describe the patient's history.

Examples include:

- Number of hospital visits
- Number of diagnoses
- Most recent encounter
- Time since last visit

These features often become strong predictors of disease progression and hospital readmission.

Step 1 — Explore Encounter Data
# 🔍 Step 15 — Explore Encounter Records

## 🏥 Real Hospital Scenario

Before creating features, healthcare analysts inspect encounter records to understand what information is available.

Typical questions include:

- How many encounters does each patient have?
- What diagnoses are recorded?
- Are encounter dates stored correctly?

---

## 🎯 What this code does

Displays the first few encounter records.

---

## ❓Why do we use it?

This verifies that the encounter dataset loaded correctly and helps us understand its structure before creating features.

In [19]:
encounters_df.head()

  patient_id encounter_id encounter_date diagnosis_code
0      P0001     EP0001_1     2023-02-21            I10
1      P0001     EP0001_2     2023-03-13            E11
2      P0001     EP0001_3     2023-04-06            I10
3      P0001     EP0001_4     2023-04-10            E11
4      P0001     EP0001_5     2023-04-10            I10

Step 2 — Count Hospital Visits

# 🏥 Step 16 — Count Patient Visits

## 🏥 Real Hospital Scenario

A patient may visit the hospital many times.

For example:

| Patient | Visits |
|----------|--------|
| P0001 | 5 |
| P0002 | 2 |
| P0003 | 8 |

Patients with frequent visits often require more healthcare resources and may have more complex medical conditions.

Instead of keeping every encounter separately, we summarize them into a single feature.

---

## 🎯 What this code does

Counts the number of encounters for each patient.

---

## ❓Why do we use it?

Hospital utilization is one of the strongest predictors used in healthcare analytics.

Patients with many encounters are often at greater risk of future hospitalization.

In [20]:
visit_counts = (
    encounters_df
    .groupby("patient_id")
    .size()
    .reset_index(name="total_visits")
)

visit_counts.head()

  patient_id  total_visits
0      P0001             5
1      P0002             5
2      P0003             6
3      P0004             5
4      P0005             6

df.groupby("patient_id").size()

Step 3 — Count Unique Diagnoses

# 🏥 Step 17 — Count Unique Diagnoses

## 🏥 Real Hospital Scenario

Your encounter table stores diagnosis codes.

For example:

| Patient | Diagnosis |
|----------|-----------|
| P0001 | E11 |
| P0001 | I10 |
| P0001 | E11 |

Although there are three encounters, there are only two unique diagnoses.

Knowing how many different conditions a patient has helps estimate disease complexity.

---

## 🎯 What this code does

Counts the number of unique diagnosis codes for every patient.

---

## ❓Why do we use it?

Patients with multiple chronic conditions generally require more complex care and often have higher healthcare utilization.

In [21]:
diagnosis_counts = (
    encounters_df
    .groupby("patient_id")["diagnosis_code"]
    .nunique()
    .reset_index(name="unique_diagnoses")
)

diagnosis_counts.head()

  patient_id  unique_diagnoses
0      P0001                 2
1      P0002                 2
2      P0003                 2
3      P0004                 2
4      P0005                 2

groupby()

↓

nunique()

Step 4 — Find the Most Recent Encounter

# 🏥 Step 18 — Latest Hospital Visit

## 🏥 Real Hospital Scenario

Doctors are often interested in a patient's latest hospital visit.

Recent healthcare utilization usually reflects the patient's current condition better than visits several years ago.

---

## 🎯 What this code does

Finds the most recent encounter date for every patient.

---

## ❓Why do we use it?

The latest encounter is useful for calculating:

- Time since last visit
- Recent healthcare utilization
- Recency-based risk scores

In [22]:
encounters_df["encounter_date"] = pd.to_datetime(
    encounters_df["encounter_date"]
)

latest_encounter = (
    encounters_df
    .groupby("patient_id")["encounter_date"]
    .max()
    .reset_index(name="last_encounter")
)

latest_encounter.head()

  patient_id last_encounter
0      P0001     2023-04-10
1      P0002     2023-02-25
2      P0003     2023-04-30
3      P0004     2023-05-31
4      P0005     2023-05-07

groupby()

↓

max()

Step 5 — Merge Encounter Features

# 🏥 Step 19 — Build the Encounter Feature Table

## 🏥 Real Hospital Scenario

Hospitals rarely use a single metric.

Instead, they combine several encounter-based features into one patient-level table.

This table becomes part of the final machine learning dataset.

---

## 🎯 What this code does

Merges all encounter features into one DataFrame.

---

## ❓Why do we use it?

Machine learning models require one row per patient.

Each column represents one feature describing that patient's healthcare history.

In [23]:
encounter_features = (
    visit_counts
    .merge(diagnosis_counts, on="patient_id")
    .merge(latest_encounter, on="patient_id")
)

encounter_features.head()

  patient_id  total_visits  unique_diagnoses last_encounter
0      P0001             5                 2     2023-04-10
1      P0002             5                 2     2023-02-25
2      P0003             6                 2     2023-04-30
3      P0004             5                 2     2023-05-31
4      P0005             6                 2     2023-05-07

df1.merge(df2)

↓

merge(df3)

How This Helps AI Models
Feature	Why It Matters
Total Visits	Measures healthcare utilization. Frequent visits may indicate higher disease burden or risk.
Unique Diagnoses	Reflects patient complexity and the presence of multiple conditions (comorbidities).
Last Encounter Date	Helps create recency-based features, such as "days since last visit," which are useful in predicting future events.

Section 5 — Medication Feature Engineering

# 💊 Introduction to Medication Feature Engineering

## 🏥 Real Hospital Scenario

Medication history is one of the strongest indicators of a patient's health status.

For example, a patient prescribed:

- Metformin
- Insulin
- Lisinopril
- Atorvastatin

is likely managing multiple chronic conditions such as diabetes, hypertension, and high cholesterol.

Instead of feeding every prescription into a machine learning model, we summarize medication history into patient-level features.

Typical medication features include:

- Total medications prescribed
- Number of unique medications
- Most recent medication
- Medication exposure

These features help AI models understand treatment intensity and disease burden.

---

## 🎯 In this section we will build

✔ Total medications prescribed

✔ Number of unique medications

✔ Most recent medication

✔ Patient medication feature table

Step 20 — Explore Medication Data

# 🔍 Explore Medication Records

## 🏥 Real Hospital Scenario

Before creating medication features, healthcare analysts inspect the pharmacy data.

Typical questions include:

- Which medications are prescribed?
- How many prescriptions exist?
- Are dates stored correctly?

---

## 🎯 What this code does

Displays the first few medication records.

---

## ❓Why do we use it?

This verifies the structure of the medication dataset before feature engineering begins.

In [24]:
medications_df.head()

  patient_id medication_name med_start_date
0      P0001      Lisinopril     2023-01-09
1      P0001       Metformin     2023-02-21
2      P0001      Lisinopril     2023-03-12
3      P0002      Lisinopril     2022-12-27
4      P0002      Lisinopril     2023-01-15

Step 21 — Count Total Medications

# 💊 Count Prescriptions per Patient

## 🏥 Real Hospital Scenario

Some patients receive only one medication.

Others receive ten or more.

Example

| Patient | Prescriptions |
|----------|--------------|
| P001 | 2 |
| P002 | 8 |
| P003 | 14 |

Patients taking many medications often have multiple chronic diseases.

---

## 🎯 What this code does

Counts how many medication records each patient has.

---

## ❓Why do we use it?

The total number of prescriptions is often used as a feature representing treatment complexity.

In [25]:
medication_counts = (
    medications_df
    .groupby("patient_id")
    .size()
    .reset_index(name="total_medications")
)

medication_counts.head()

  patient_id  total_medications
0      P0001                  3
1      P0002                  3
2      P0003                  1
3      P0004                  1
4      P0005                  2

df.groupby("patient_id").size()

Step 22 — Count Unique Medications

# 💊 Count Unique Medications

## 🏥 Real Hospital Scenario

A patient may receive Metformin multiple times.

We often care about how many different medications the patient is taking.

Example

| Patient | Medications |
|----------|-------------|
| Metformin |
| Metformin |
| Insulin |

Unique medications = 2

---

## 🎯 What this code does

Counts unique medication names for each patient.

---

## ❓Why do we use it?

Patients receiving many different medications often have more complicated treatment plans.

In [26]:
unique_medications = (
    medications_df
    .groupby("patient_id")["medication_name"]
    .nunique()
    .reset_index(name="unique_medications")
)

unique_medications.head()

  patient_id  unique_medications
0      P0001                   2
1      P0002                   1
2      P0003                   1
3      P0004                   1
4      P0005                   2

Step 23 — Find the Most Recent Medication

# 📅 Latest Medication

## 🏥 Real Hospital Scenario

Doctors often focus on the patient's most recently prescribed medication because it reflects the current treatment plan.

Example

| Date | Medication |
|------|------------|
| Jan | Metformin |
| Mar | Insulin |
| Jun | Semaglutide |

Latest medication = Semaglutide

---

## 🎯 What this code does

Finds the latest medication prescribed to each patient.

---

## ❓Why do we use it?

Recent medication history is often more predictive than medications prescribed years ago.

In [27]:
medications_df["med_start_date"] = pd.to_datetime(
    medications_df["med_start_date"]
)

latest_medication = (
    medications_df
    .sort_values("med_start_date")
    .groupby("patient_id")
    .last()
    .reset_index()[["patient_id", "medication_name", "med_start_date"]]
)

latest_medication.head()

  patient_id medication_name med_start_date
0      P0001      Lisinopril     2023-03-12
1      P0002      Lisinopril     2023-03-05
2      P0003      Lisinopril     2022-12-04
3      P0004       Metformin     2022-12-11
4      P0005      Lisinopril     2023-01-20

sort_values()

↓

groupby()

↓

last()

Step 24 — Merge Medication Features

# 🔗 Build Medication Feature Table

## 🏥 Real Hospital Scenario

Hospitals combine multiple medication-related features into one patient-level table.

Instead of storing every prescription separately, each patient receives one summarized record.

---

## 🎯 What this code does

Combines all medication features into one table.

---

## ❓Why do we use it?

Machine learning models require one row per patient, with each column representing a meaningful feature.

In [28]:
medication_features = (
    medication_counts
    .merge(unique_medications, on="patient_id")
    .merge(latest_medication, on="patient_id")
)

medication_features.head()

,patient_id,total_medications,unique_medications,medication_name,med_start_date
0,P0001,3,2,Lisinopril,2023-03-12
1,P0002,3,1,Lisinopril,2023-03-05
2,P0003,1,1,Lisinopril,2022-12-04
3,P0004,1,1,Metformin,2022-12-11
4,P0005,2,2,Lisinopril,2023-01-20

df1.merge(df2)

↓

merge(df3)

How This Helps AI Models
Feature	Why It Matters
Total Medications	Indicates treatment intensity and healthcare utilization.
Unique Medications	Reflects disease complexity and polypharmacy.
Latest Medication	Represents the patient's current treatment regimen and can signal recent clinical changes.

Section 6 — Merge Healthcare Feature Tables

# 🔗 Introduction to Feature Table Integration

## 🏥 Real Hospital Scenario

Hospitals rarely build AI models directly from one system.

Instead, patient information is scattered across multiple healthcare systems.

For example:

Electronic Health Record (EHR)

↓

Hospital Visits

Laboratory Information System (LIS)

↓

Laboratory Results

Pharmacy System

↓

Medication History

Each system provides only part of the patient's story.

Before training a machine learning model, data engineers combine these separate datasets into a single patient-level table.

This process is called **feature integration** or **feature table merging**.

The final dataset contains:

- One row = One patient
- One column = One feature

This is the format expected by most machine learning algorithms.

In [29]:
print("=== Laboratory Features ===")
display(lab_features.head())

print("=== Encounter Features ===")
display(encounter_features.head())

print("=== Medication Features ===")
display(medication_features.head())

=== Laboratory Features ===

lab_name patient_id     Glucose
0             P0001  122.675000
1             P0002  113.483333
2             P0003  125.480000
3             P0004  130.600000
4             P0005  128.780000

=== Encounter Features ===

  patient_id  total_visits  unique_diagnoses last_encounter
0      P0001             5                 2     2023-04-10
1      P0002             5                 2     2023-02-25
2      P0003             6                 2     2023-04-30
3      P0004             5                 2     2023-05-31
4      P0005             6                 2     2023-05-07

=== Medication Features ===

,patient_id,total_medications,unique_medications,medication_name,med_start_date
0,P0001,3,2,Lisinopril,2023-03-12
1,P0002,3,1,Lisinopril,2023-03-05
2,P0003,1,1,Lisinopril,2022-12-04
3,P0004,1,1,Metformin,2022-12-11
4,P0005,2,2,Lisinopril,2023-01-20

display(df.head())

Step 26 — Merge Laboratory and Encounter Features

# 🔗 Merge Laboratory and Encounter Features

## 🏥 Real Hospital Scenario

Suppose Patient P001 appears in:

Laboratory System

↓

Average Glucose

↓

Hospital System

↓

Total Visits

These features belong to the same patient.

By merging on **patient_id**, we combine information from different systems into one patient record.

---

## 🎯 What this code does

Combines laboratory features with encounter features.

---

## ❓Why do we use it?

Instead of keeping two separate datasets, we create one richer patient profile.

In [30]:
patient_features = pd.merge(
    lab_features,
    encounter_features,
    on="patient_id",
    how="outer"
)

patient_features.head()

  patient_id     Glucose  total_visits  unique_diagnoses last_encounter
0      P0001  122.675000             5                 2     2023-04-10
1      P0002  113.483333             5                 2     2023-02-25
2      P0003  125.480000             6                 2     2023-04-30
3      P0004  130.600000             5                 2     2023-05-31
4      P0005  128.780000             6                 2     2023-05-07

pd.merge(df1, df2, on="patient_id")

Step 27 — Merge Medication Features

# 🔗 Add Medication Features

## 🏥 Real Hospital Scenario

Our patient profile is still incomplete.

Medication history provides valuable information about disease management and treatment.

We now combine medication features with the existing patient dataset.

---

## 🎯 What this code does

Adds medication features to the merged patient dataset.

---

## ❓Why do we use it?

This creates a more complete representation of each patient's clinical history.

In [31]:
patient_features = patient_features.merge(
    medication_features,
    on="patient_id",
    how="outer"
)

patient_features.head()

,patient_id,Glucose,total_visits,unique_diagnoses,last_encounter,total_medications,unique_medications,medication_name,med_start_date
0,P0001,122.675000,5,2,2023-04-10,3,2,Lisinopril,2023-03-12
1,P0002,113.483333,5,2,2023-02-25,3,1,Lisinopril,2023-03-05
2,P0003,125.480000,6,2,2023-04-30,1,1,Lisinopril,2022-12-04
3,P0004,130.600000,5,2,2023-05-31,1,1,Metformin,2022-12-11
4,P0005,128.780000,6,2,2023-05-07,2,2,Lisinopril,2023-01-20

df.merge(
    another_df,
    on="patient_id"
)

Step 28 — Check Missing Values After Merge

# 🔍 Check Missing Values

## 🏥 Real Hospital Scenario

Not every patient has information in every healthcare system.

For example:

- A patient may have laboratory tests but no medications.
- Another patient may have medications but no laboratory tests.

After merging, missing values naturally appear.

---

## 🎯 What this code does

Counts missing values in the merged dataset.

---

## ❓Why do we use it?

This helps us understand which features require imputation before machine learning.

In [32]:
patient_features.isnull().sum()

patient_id            0
Glucose               0
total_visits          0
unique_diagnoses      0
last_encounter        0
total_medications     0
unique_medications    0
medication_name       0
med_start_date        0
dtype: int64

df.isnull().sum()

Step 29 — Handle Missing Values

# 🧹 Handle Missing Values

## 🏥 Real Hospital Scenario

Missing data is common in healthcare.

Example:

A patient who never had a glucose test should not cause the model to fail.

Instead, we replace missing values using simple rules.

For this portfolio project:

- Numeric features → Replace with 0
- Text features → Replace with "Unknown"

> **Note:** In real healthcare projects, the imputation strategy depends on the clinical meaning of the feature. For example, a missing lab result may not always mean zero—it could mean the test was never performed.

---

## 🎯 What this code does

Fills missing values in the merged feature table.

---

## ❓Why do we use it?

Most machine learning algorithms cannot work with missing values.

Handling missing data ensures the dataset is complete and ready for modeling.

In [ ]:
#our data dont have  missing value  but if have we can run this code
# Fill numeric columns
numeric_columns = patient_features.select_dtypes(include="number").columns

patient_features[numeric_columns] = (
    patient_features[numeric_columns]
    .fillna(0)
)

# Fill text columns
text_columns = patient_features.select_dtypes(include="object").columns

patient_features[text_columns] = (
    patient_features[text_columns]
    .fillna("Unknown")
)

patient_features.head()

fillna()

Step 30 — Verify the Final Feature Table

# 📊 Verify the Final Dataset

## 🏥 Real Hospital Scenario

Before sending data to a data scientist or machine learning pipeline, healthcare engineers perform a final validation.

Typical checks include:

- Number of patients
- Number of features
- Missing values
- Dataset structure

---

## 🎯 What this code does

Displays the size of the final patient-level dataset.

---

## ❓Why do we use it?

This confirms that feature integration was successful and that the dataset is ready for the next stage.

# 📊 Verify the Final Dataset

## 🏥 Real Hospital Scenario

Before sending data to a data scientist or machine learning pipeline, healthcare engineers perform a final validation.

Typical checks include:

- Number of patients
- Number of features
- Missing values
- Dataset structure

---

## 🎯 What this code does

Displays the size of the final patient-level dataset.

---

## ❓Why do we use it?

This confirms that feature integration was successful and that the dataset is ready for the next stage.

In [33]:
print("Final Dataset Shape:", patient_features.shape)

display(patient_features.head())

Final Dataset Shape: (400, 9)

,patient_id,Glucose,total_visits,unique_diagnoses,last_encounter,total_medications,unique_medications,medication_name,med_start_date
0,P0001,122.675000,5,2,2023-04-10,3,2,Lisinopril,2023-03-12
1,P0002,113.483333,5,2,2023-02-25,3,1,Lisinopril,2023-03-05
2,P0003,125.480000,6,2,2023-04-30,1,1,Lisinopril,2022-12-04
3,P0004,130.600000,5,2,2023-05-31,1,1,Metformin,2022-12-11
4,P0005,128.780000,6,2,2023-05-07,2,2,Lisinopril,2023-01-20

How This Helps AI Models & Dashboards

Imagine you're building a 30-day hospital readmission prediction model.

Instead of giving the model thousands of raw events, you provide a single summarized patient record:

Patient	Avg Glucose	Total Visits	Total Medications	Unique Diagnoses
P001	165	5	4	3

This structured format makes it much easier for:

🤖 Machine learning models to learn patterns.
📊 Dashboards to display patient-level metrics.
🏥 Clinicians to interpret results.

Section 7 — AI Preparation & Model-Ready Dataset

# 🤖 Introduction to AI Preparation

## 🏥 Real Hospital Scenario

After combining data from the Electronic Health Record (EHR), Laboratory System, and Pharmacy System, healthcare organizations are almost ready to train an AI model.

However, before model training, data engineers perform a final preparation step.

The goals are to:

- Select useful features
- Remove unnecessary columns
- Prevent data leakage
- Export a clean dataset for machine learning

At the end of this section, we will have a **model-ready dataset** where:

- One row = One patient
- One column = One feature

This is the format expected by machine learning libraries such as Scikit-learn, XGBoost, TensorFlow, and PyTorch.

Step 31 — Review Available Features

# 🔍 Review Available Features

## 🏥 Real Hospital Scenario

Before building a predictive model, healthcare data scientists review all available variables.

Not every column is useful for machine learning.

Some columns are identifiers.

Some contain text.

Others are excellent predictive features.

---

## 🎯 What this code does

Displays every column in the patient feature table.

---

## ❓Why do we use it?

This helps us decide:

- Which columns become model features
- Which columns should be removed

In [34]:
patient_features.columns

Index(['patient_id', 'Glucose', 'total_visits', 'unique_diagnoses',
       'last_encounter', 'total_medications', 'unique_medications',
       'medication_name', 'med_start_date'],
      dtype='object')

Step 32 — Select AI Features

# 🎯 Select Features for Machine Learning

## 🏥 Real Hospital Scenario

Not every column should be used for training.

For example:

✔ Average Glucose

✔ Total Visits

✔ Unique Diagnoses

✔ Total Medications

are useful predictors.

However,

Patient IDs

are identifiers and should not influence predictions.

---

## 🎯 What this code does

Creates a new DataFrame containing only the features used for machine learning.

---

## ❓Why do we use it?

Machine learning models should learn from patient characteristics, not patient identities.

In [35]:
model_data = patient_features.drop(columns=["patient_id"])

model_data.head()

,Glucose,total_visits,unique_diagnoses,last_encounter,total_medications,unique_medications,medication_name,med_start_date
0,122.675000,5,2,2023-04-10,3,2,Lisinopril,2023-03-12
1,113.483333,5,2,2023-02-25,3,1,Lisinopril,2023-03-05
2,125.480000,6,2,2023-04-30,1,1,Lisinopril,2022-12-04
3,130.600000,5,2,2023-05-31,1,1,Metformin,2022-12-11
4,128.780000,6,2,2023-05-07,2,2,Lisinopril,2023-01-20

Patient Dataset

↓

Remove IDs

↓

AI Dataset

Step 33 — Prevent Data Leakage
# 🛡️ Prevent Data Leakage

## 🏥 Real Hospital Scenario

One of the biggest mistakes in healthcare AI is using information that would not have been available when the prediction was made.

Example

Suppose we want to predict whether a patient will be readmitted within 30 days.

The model **cannot** use:

- future laboratory tests
- future medications
- future diagnoses

because those events happen **after** the prediction date.

Using future information gives the model an unfair advantage and leads to unrealistic performance.

This problem is called **Data Leakage**.

---

## 🎯 What this code does

Removes columns that contain future information or should not be used for prediction.

---

## ❓Why do we use it?

A trustworthy healthcare model must only use information available **up to the prediction date**.

In [36]:
columns_to_remove = [
    "last_encounter",
    "med_start_date"
]

model_data = model_data.drop(
    columns=columns_to_remove,
    errors="ignore"
)

model_data.head()

,Glucose,total_visits,unique_diagnoses,total_medications,unique_medications,medication_name
0,122.675000,5,2,3,2,Lisinopril
1,113.483333,5,2,3,1,Lisinopril
2,125.480000,6,2,1,1,Lisinopril
3,130.600000,5,2,1,1,Metformin
4,128.780000,6,2,2,2,Lisinopril

drop()

↓

Future Variables

↓

Leakage Prevention

tep 34 — Review Final Dataset

# 📊 Final Dataset Review

## 🏥 Real Hospital Scenario

Before training begins, healthcare engineers perform one final quality check.

Typical questions include:

- How many patients?
- How many features?
- Any missing values?

---

## 🎯 What this code does

Displays the size of the final AI dataset.

---

## ❓Why do we use it?

This confirms that the dataset is complete and ready for machine learning.

In [37]:
print("Model Dataset Shape")

print(model_data.shape)

display(model_data.head())

Model Dataset Shape
(400, 6)

,Glucose,total_visits,unique_diagnoses,total_medications,unique_medications,medication_name
0,122.675000,5,2,3,2,Lisinopril
1,113.483333,5,2,3,1,Lisinopril
2,125.480000,6,2,1,1,Lisinopril
3,130.600000,5,2,1,1,Metformin
4,128.780000,6,2,2,2,Lisinopril

shape

↓

Review

↓

Ready

Step 35 — Export the Model-Ready Dataset# 💾 Export the Final Dataset

## 🏥 Real Hospital Scenario

Once feature engineering is complete, the dataset is exported.

This exported file is typically passed to:

- Data Scientists
- Machine Learning Engineers
- Business Intelligence teams

The same dataset may also be stored in a healthcare data warehouse for reporting.

---

## 🎯 What this code does

Exports the model-ready dataset as a CSV file.

---

## ❓Why do we use it?

The exported dataset becomes the starting point for:

- Predictive models
- Dashboards
- Clinical analytics

In [38]:
model_data.to_csv(
    "model_ready_dataset.csv",
    index=False
)

print("✅ Model-ready dataset exported successfully!")

✅ Model-ready dataset exported successfully!

How This Affects AI Models & Dashboards
🤖 Machine Learning

The exported dataset can now be used to train models such as:

Logistic Regression
Random Forest
XGBoost
LightGBM
Neural Networks

Example predictions:

30-day hospital readmission
Diabetes complications
ICU admission
Sepsis risk
Length of stay
📈 Business Intelligence

The same dataset can power dashboards that show:

Average HbA1c by patient
Total hospital visits
Medication utilization
Chronic disease burden
Patient risk stratification

Instead of querying three separate systems, analysts can work from one integrated patient-level dataset.

🎉 Project Summary
Raw Healthcare Data
        │
        ▼
Load & Explore Data
        │
        ▼
Assess Data Quality
        │
        ▼
Laboratory Feature Engineering
        │
        ▼
Encounter Feature Engineering
        │
        ▼
Medication Feature Engineering
        │
        ▼
Merge Feature Tables
        │
        ▼
Handle Missing Values
        │
        ▼
Select AI Features
        │
        ▼
Prevent Data Leakage
        │
        ▼
Export Model-Ready Dataset
        │
        ▼
Machine Learning / Dashboard